### PR TITLE
Remove excessive parts of package.json

### PR DESCRIPTION
**Pull request by zdroid**
- Remove duplicate keywords
- Use simpler version of repository
- Remove homepage and bugs as they are are pre-included the same way

I've also noticed npm pkg's name is "endangered-languages" and not "low-resource-languages". Is that a mistake on npm or here?

### CODE REVIEW

**Comment by RichardLitt** [comment]
> I've also noticed npm pkg's name is "endangered-languages" and not "low-resource-languages". Is that a mistake on npm or here?

No, that used to be the name of this repo. It's not a significant enough thing to change, I think. 

> Remove homepage and bugs as they are are pre-included the same way

Do you have documentation for this? They are separate fields according to the [spec](https://docs.npmjs.com/files/package.json#homepage).

**Comment by zdroid** [comment]
Maybe you are right that those aren't officially supported. I will check this in a few days.

**Comment by zdroid** [comment]
I checked both npmjs.org page and npm cli output for my npm package `percent`. All fields are shown there, but it seems it isn't clearly stated on the website. I made an official request to clear this. npm/cli#516

The changes I've made in this PR for `keywords` and `repository` are surely supported.

**Comment by RichardLitt** [comment]
Thanks, @zdroid. In the meantime, let's just merge this. Good work!

**Pull request merged**
