### PR TITLE
Add mention of Persephone

### PR DESCRIPTION
**Pull request by alexis-michaud**
Persephone is designed for situations where training data is limited, perhaps as little as an hour of transcribed speech. Such limitations on data are common in the documentation of low-resource languages. It is possible to use such small amounts of data to train a transcription model that can help aid transcription, yet such technology has not been widely adopted. The goal of Persephone is thus to make state-of-the-art phonemic transcription accessible to people involved in language documentation. It is more flexible than CMU-Sphinx in that it handles a wider range of phenomena (including linguistic tone) and yields good results, as reported in recent work: Adams, Oliver, Trevor Cohn, Graham Neubig, Hilaria Cruz, Steven Bird & Alexis Michaud. 2018. Evaluating phonemic transcription of low-resource tonal languages for language documentation. Proceedings of LREC 2018 (Language Resources and Evaluation Conference), 3356–3365. Miyazaki. https://halshs.archives-ouvertes.fr/halshs-01709648.

### CODE REVIEW

**Comment by RichardLitt** [comment]
What a great addition! Thank you, @alexis-michaud.

**Comment by alexis-michaud** [comment]
:smiley: Thanks for this great `low-resource-languages` repository!

A thought concerning another, complementary project: wouldn't there also be great value in a list of available data sets of 'Acutely Under-Resourced Languages' (to use a phrase from [a paper concerning ASR for Seneca](http://www.lrec-conf.org/proceedings/lrec2018/pdf/749.pdf)) that are ready for Natural Language Processing? 

Oliver Adams points out that such data sets are difficult to access, and that this slows down experiments with state-of-the-art computational tools for language documentation. See for instance some reflections in [his PhD dissertation](http://hdl.handle.net/11343/210811), §7.3.1, p. 176:  

> [Such data sets] are often not easily attainable and is often quarantined behind legal agreements.
> When it is accessible, the data is formatted in different ways and may require significant
> preprocessing to make them consistently amenable to a given machine learning
> method

Thus, someone aiming at the ambitious goal of doing language-independent transcription in the International Phonetic Alphabet would want to 'harvest' a set of diverse corpora (audio+transcriptions in IPA) from online repositories without having to spend no end of time contacting linguists one by one. As you know, there is a wonderful world-wide organization that lists existing resources language by language, [OLAC](http://www.language-archives.org/), but wouldn't there nonetheless be room for a NLP-oriented list devised for computer scientists?

To keep the project within reasonable proportions, it could focus on maintaining a detailed list of **data sets that have already been used in at least one NLP experiment**, for instance [this Chatino data set](https://scholarworks.iu.edu/dspace/handle/2022/21028). Each data set would be listed. The list is probably not huge, and these sets are likely to be the most appealing to computer scientists because there is a sense of a shared goal / challenge and also preprocessing is likely to be feasible. 

(The idea of listing only resources that have 1 associated publication comes from [this repository for signal-processing software](https://covarep.github.io/covarep/). The restriction could be loosened to: include all datasets that have been used in NLP tests, whether reported in a publication or not.)

Of course the page would also provide a link to [OLAC](http://www.language-archives.org/) and a couple other websites that list archives that host language data of all sorts, with the caveat to computer science users that there may be quite a lot of work to do to preprocess such data sets. 

I wonder who could set up such an inventory. Maybe phoneticians? but I fear that the project won't be high-priority for them. Or -- ideally -- an interdisciplinary group of phoneticians, computer science specialists and fieldworkers interested to work with one another?

**Comment by RichardLitt** [comment]
Yes; I think that this would serve a very important function in the current NLP for LRL ecosystem. The difficulty, as you point out, may be more sourcing the information than anything else. I don't think providing OLAC links would be too difficult. My immediate approach would be to clone a GitHub repository and then publish a paper on it (that's what I did here, to mixed results). 

Working with data is difficult, because even if a data source has been used in an NLP paper, it doesn't mean that that data will be available to anyone else. As well, ensuring data longevity isn't easy, and isn't something I can really offer at the moment. 

I wish I had the time to dedicate to this, but at the moment, I do not.

**Comment by HughP** [comment]
@alexis-michaud 
The idea of providing content to OLAC has been modeled in one of these repos here or my copy in my user space. The the technical challenge has been moving the awesome-list format to a format that can be converted to OLAC XML. I have toyed with the idea of using Travis CI to search Github for a specially formatted file, which would be a mash-up of DOAP and OLAC metadata. And going around to projects which are listed in this awesome list and pushing the file to them with a notice to their maintainers. Then using some server side logic to filter and parse the API return so that project data about the content including the language can be formatted for OLAC. 

If you want to pursue this further with me I am open to that. I'll be at LLACAN after September 2019, if an in person collaboration is possible at that time. Otherwise a virtual collaboration some time after January 2019 would be possible.

**Comment by alexis-michaud** [comment]
In-person collaboration at the *centre Haudricourt* this Autumn sounds great! Can't wait. 

I'm in *bâtiment D*, room 204A.

**Pull request merged**
