### PR TITLE
Remove obsolete add_stars.sh

### PR DESCRIPTION
**Pull request by AurelienLourot**
Hi @RichardLitt, we know each other from https://github.com/RichardLitt/low-resource-languages/pull/140.

If I understood correctly you stopped using these star badges because they are often not resolved in time. 

I'm also using this opportunity to define an icon for this repo on ghuser.io, a project I'm working on for building **complete** GitHub profiles like http://ghuser.io/RichardLitt (this is supposed to list all repos you have ever touched on GitHub, sorted by relevance. And yes, the list is massive in your case!)

Of course feel free to decline that file if you don't like it, no problem :)

### CODE REVIEW

**Comment by AurelienLourot** [comment]
> Is there any way for you to define the user icon on ghuser.io, and not in this repo?

Yes this will be possible soon as well. OK then I'll remove it from this PR. 

Also I'm fixing the links which made Travis red.

**Comment by RichardLitt** [comment]
Thanks! Adding data here doesn't seem like the best option for having information on another site. I do like the site, though!

**Comment by AurelienLourot** [comment]
thanks :) 

so I have fixed all the links except the ones to gramatica.usc.es. It seems like this server is temporarily down. For example the first project CitiusTagger, I managed to find it here: https://github.com/citiususc/Linguakit#pos-tagger . And there they are still linking to gramatica.usc.es as well. Also Google still remembers gramatica.usc.es. I'm not sure what to do, but if you want I can replace these links to gramatica.usc.es with links to GitHub, or we could just wait and see if the server behind this subdomain is coming back up.

**Comment by RichardLitt** [comment]
Thank you! No worries about that, it happens. As long as the majority of the links aren't broken I'm happy.

**Pull request merged**
